### ISSUE TITLE
qq无法访问dcim

### ISSUE THREAD

**Issue by xiangyu0** [wenxuanjun/NoLitter#10]
qq似乎无法访问dcim文件夹了，能否增加一个允许应用单独访问一些文件夹的功能

**Comment by xiangyu0** [comment]
经查询与排查，确认是由于强力模式导致的，不知道是否算是一个bug？

**Comment by wenxuanjun** [comment]
1. 请仔细查看强力模式的描述：启用后，将无条件重定向任何文件请求
2. 白名单功能将在以后的版本中被加入
