### ISSUE TITLE
微信侧漏严重

### ISSUE THREAD

**Issue by xiangyu0** [wenxuanjun/NoLitter#11]
即使开启微信的强力模式，下载的文件仍不能重定向到/storage/emulated/0/Android/data/com.tencent.mm/sdcard/Android/data/com.tencent.mm/MicroMsg/Download/文件夹中，还是会保存在原来的/storage/emulated/0/Android/data/com.tencent.mm/MicroMsg/Download/文件夹，但是发送图片时就是完全无法读取picture与dcim文件夹

**Comment by wenxuanjun** [comment]
你的问题不太明晰，标题与内容不符，现暂且关闭此 Issue。若还有其他问题，你可以再次打开。
