### ISSUE TITLE
英语翻译错误

### ISSUE THREAD

**Issue by deltazefiro** [wenxuanjun/NoLitter#5]
## 描述
主页的 `应用` 与 `对应用进行单独设置`  
被译为 `General` 和 `Several commonly used settings`  
(顺便问一下 这个单独设置是啥？)

## 定位
https://github.com/wenxuanjun/NoLitter/blob/e4acb402b38570b2226f34da1b78d06fa06aac76/app/src/main/res/values/strings.xml#L16-L17  
https://github.com/wenxuanjun/NoLitter/blob/e4acb402b38570b2226f34da1b78d06fa06aac76/app/src/main/res/values-zh/strings.xml#L16-L17

## 截图
![](https://raw.githubusercontent.com/deltazefiro/ImageHost/master/NoLitter-eng.jpg)

**Comment by wenxuanjun** [comment]
抱歉，这是复制粘贴后忘记修改了，将立刻改正。

单独设置指可以单独对某个应用设置强力模式、允许访问公共目录、启用额外的钩子和重定向风格这四个选项，与 `General` 里的全局设置相对。

感谢您提交的 Issue。
