### ISSUE TITLE
「强力模式」似乎存在一些无脑的问题

### ISSUE THREAD

**Issue by MisaLiu** [wenxuanjun/NoLitter#7]
开启强力模式后，所有对 `/sdcard` 的访问都会被重定向至 `/sdcard/Android/data/app.package.name/sdcard`。

但与此同时，应用对自身私有目录的访问会被重定向到 `/sdcard/Android/data/app.package.name/sdcard/Android/data/app.package.name` 下，变成套娃结果。

**Comment by wenxuanjun** [comment]
应该已成功修复。
