### ISSUE TITLE
在应用设置中增加搜索应用的功能

### ISSUE THREAD

**Issue by xiangyu0** [wenxuanjun/NoLitter#8]
在应用设置中增加搜索应用的功能，另外现在新版的作用域选择哪些app呢

**Comment by wenxuanjun** [comment]
此功能将在`1.6.0-beta`中加入。作用域仍然只需要选择需要被重定向的应用。

**Comment by xiangyu0** [comment]
好的，请问到时候也是在这里下载吗，另外现在如果要正常使用是不是既要勾选作用域，又要在模块设置里的应用界面勾选开启呢

**Comment by wenxuanjun** [comment]
只需要勾选作用域即可。

如 #5 中所说，模块设置里的应用单独设置指的是相对与全局设置的，与重定向相关的选项。若不需要单独设置，则无需开启

**Comment by xiangyu0** [comment]
好的谢谢，辛苦解答
